import os
import yaml

DEFAULT_CONFIG = {
    "rules": {
        "long_function": {
            "enabled": True,
            "max_lines": 30,
        },
        "duplicate_code": {
            "enabled": True,
            "min_block_lines": 6,
            "similarity_threshold": 0.8,
            "max_comparisons": 5000,
        },
        "complex_condition": {
            "enabled": True,
            "max_depth": 3,
        },
        "temporary_field": {
            "enabled": True,
        },
    },
    "refactoring": {
        "auto_apply": False,
        "confirm_before_apply": True,
        "backup": True,
    },
    "ignore_patterns": [
        "__pycache__",
        ".git",
        ".venv",
        "venv",
        "env",
        ".tox",
        "node_modules",
        "*.pyc",
    ],
    "vcs": {
        "skip_untracked": True,
    },
    "output": {
        "report_format": "text",
        "report_path": None,
    },
}

CONFIG_FILE_NAMES = [".pyrefactor.yaml", "pyrefactor.yaml", ".pyrefactor.yml", "pyrefactor.yml"]


def find_config_file(start_dir: str) -> str:
    current = os.path.abspath(start_dir)
    while True:
        for name in CONFIG_FILE_NAMES:
            candidate = os.path.join(current, name)
            if os.path.isfile(candidate):
                return candidate
        parent = os.path.dirname(current)
        if parent == current:
            break
        current = parent
    return None


def load_config(config_path=None, project_root=None):
    config = dict_deep_copy(DEFAULT_CONFIG)

    if config_path is not None:
        if os.path.exists(config_path):
            with open(config_path, "r", encoding="utf-8") as f:
                user_config = yaml.safe_load(f) or {}
            deep_merge(config, user_config)
    else:
        search_dir = project_root if project_root else os.getcwd()
        if os.path.isfile(search_dir):
            search_dir = os.path.dirname(search_dir)
        auto_path = find_config_file(search_dir)
        if auto_path and os.path.exists(auto_path):
            with open(auto_path, "r", encoding="utf-8") as f:
                user_config = yaml.safe_load(f) or {}
            deep_merge(config, user_config)

    return config


def dict_deep_copy(source):
    result = {}
    for key, value in source.items():
        if isinstance(value, dict):
            result[key] = dict_deep_copy(value)
        elif isinstance(value, list):
            result[key] = list(value)
        else:
            result[key] = value
    return result


def deep_merge(base, override):
    for key, value in override.items():
        if key in base and isinstance(base[key], dict) and isinstance(value, dict):
            deep_merge(base[key], value)
        else:
            base[key] = value


def is_rule_enabled(config, rule_name):
    rule_config = config.get("rules", {}).get(rule_name, {})
    return rule_config.get("enabled", False)


INIT_CONFIG_TEMPLATE = """\
# PyRefactor Configuration
# ========================
# This file is auto-generated by 'pyrefactor init'.
# Modify the values below to customize the behavior of the tool.

rules:
  # ----- Long Function Detection -----
  # Detects functions and methods that exceed a specified line count.
  # A long function is a sign that it may be doing too much and should
  # be split into smaller, focused functions.
  long_function:
    enabled: true           # Set to false to disable this rule
    max_lines: 30           # Maximum allowed lines for a function/method

  # ----- Duplicate Code Detection -----
  # Detects code blocks that are structurally similar to each other.
  # Duplicate code makes maintenance harder: a bug fix in one place
  # must be manually replicated in all copies.
  duplicate_code:
    enabled: true           # Set to false to disable this rule
    min_block_lines: 6      # Minimum lines a block must have to be compared
    similarity_threshold: 0.80  # 0.0-1.0, similarity ratio to flag as duplicate
    max_comparisons: 5000   # Maximum pairwise comparisons to perform

  # ----- Complex Condition Nesting -----
  # Detects if-statements and while-loops nested deeper than a threshold.
  # Deep nesting makes code harder to read, test, and reason about.
  # Consider extracting nested conditions or using early returns.
  complex_condition:
    enabled: true           # Set to false to disable this rule
    max_depth: 3            # Maximum allowed nesting depth for conditions

  # ----- Temporary Field Detection -----
  # Detects instance attributes that are only used as "scratchpad"
  # variables to pass data between methods. These indicate an unclear
  # responsibility split in the class design.
  temporary_field:
    enabled: true           # Set to false to disable this rule

# Refactoring behavior
refactoring:
  auto_apply: false             # Apply refactorings without prompt (CLI --auto)
  confirm_before_apply: true    # Ask for confirmation before modifying files
  backup: true                  # Create .bak backup files before modification

# Directories and file patterns to skip during scanning
ignore_patterns:
  - __pycache__
  - .git
  - .venv
  - venv
  - env
  - .tox
  - node_modules
  - "*.pyc"

# Version control integration
vcs:
  skip_untracked: true    # Skip files not tracked by Git (use --no-vcs to override)

# Report output settings
output:
  report_format: text     # Default format: 'text' or 'json'
  report_path: null       # Path to save report; null = print to stdout
"""


def generate_init_config(target_path: str) -> str:
    target_path = os.path.abspath(target_path)
    if os.path.isdir(target_path):
        target_path = os.path.join(target_path, "pyrefactor.yaml")
    with open(target_path, "w", encoding="utf-8") as f:
        f.write(INIT_CONFIG_TEMPLATE)
    return target_path